
zuul:  routes:    convert-service:
      path: /convert/**
      #serviceId: convert-service
      strip-prefix: false

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9000/eureka/
  
  server:
    eviction-interval-timer-in-ms: 10000
    
spring:
  application:
    name: zuul-proxy-service
